### ISSUE TITLE
Unable to open app with Section Access

### ISSUE THREAD

**Issue by Diamant024** [qlik-oss/core#9]
I imported app having Section Access created in Qlik Sense. When I try open it, using function `openDoc()`, Core gives me error `Section access detected when opening an app in QlikView Personal`.

When I call function `getAuthenticatedUser()` it returns correct account which has access to this app.

What am I doing wrong?

**Comment by axelssonHakan** [comment]
We had a look at the code and it seems that the Engine has to be started with JWT support. 
https://core.qlik.com/tutorials/authorization/#qlik-associative-engine-configuration

The `sub` in the **JWT** will be mapped to `USERID` and can then be used in **Section Access**

Could you please verify that this solves your use case. We will and some note in the documentation that JWT has to be enabled

**Comment by axelssonHakan** [comment]
@Diamant024 Is it OK to close this issue?
